### ISSUE TITLE
Loading next trains

### ISSUE THREAD

**Issue by romainhugot** [jvanoost/MMM-SNCF#1]
Salut jvanoost,
Merci pour ce travail. Ton module serait super pratique pour moi en revanche je n'arrive pas à le faire fonctionner. J'ai bien la clé api de la sncf. Il y a des lettres et des chiffres avec des tirets. Sur mon miroir je n'ai que "loading next train." Dans un mail que j'ai reçu la sncf dit de mettre la clé en login et de laisser vide le mdp. Est-ce bien ça ? Merci d'avance de ton aide

**Comment by xonlly** [comment]
Oui il faut bien uniquement le login avec le token, dans le code il a bien fait la modification. Mais j'ai aussi le problème, je cherche une solution. Je te dit si j'en trouve une ;)

**Comment by romainhugot** [comment]
Salut  Merci de ton retour. En fait j'ai finalement réussi à faire fonctionner le module. Mon problème semble venir des données concernant les gares de Lyon. En effet, en renseignant les gares de Grenoble (UIC n°87747006) et la Verpillère (UIC n° 87723395) j'ai un résultat qui s'affiche sur mon miroir. En revanche en renseignant les gares de La verpillère (UIC n° 87723395) et Lyon Part dieu (UIC n° 87723197) ou Lyon Jean-Macé (UIC n° 87282624), là ça ne fonctionne plus.
En tout cas merci à toi

**Comment by xonlly** [comment]
Dac top ;) Pour ma part j'ai fait quelques modifications ici https://github.com/jvanoost/MMM-SNCF/pull/2 

Il y avait des problèmes avec des horaires de quelques gares, j'affiche aussi un message si il n'y a aucun train.

Je vais surement proposé un autre fix plus tard. Car aujourd'hui il ne gère pas les doubles modules. 

Bonne soirée !

**Comment by tsoonav** [comment]
Bonjour et désolé du gros retard de réponse, je n'avais pas eu les notifications.
Merci pour les évolutions !
J'ai encore un problème avec les retards qui ne s'affichent pas normalement...
Et c'est mon premier module, je suis encore loin d'être parfait.
J'avais regardé pour gérer le double module mais je me suis perdu dans le code ...

**Comment by chassain** [comment]
Bonjour,

Module très intéressant mais je note beaucoup de problème avec certaines stations. Impossible de faire afficher un toulon paris..
Qu'en est il des évolutions ?

**Comment by tsoonav** [comment]
Bonjour,
Etrange que votre Toulon-Paris ne s'affiche pas.

Vous récupérez bien les données via l'API SNCF ?
Quels sont vos identifiants de gares ?

Bonne journée

**Comment by chassain** [comment]
Bonjour,

Voici les identifiants pour un Toulon Paris j'ai :
stop_area:OCE:SA:87755009
stop_area:OCE:SA:876860006

Du coup je fais un toulon marseille ok et marseille paris ok

Je récupère ces identifiants via l api et la console qui me donne bien les horaires de tous les departs de toulon 

Merci

**Comment by tsoonav** [comment]
Si je comprends bien, du coup pour faire le Toulon Paris, vous avez un changement à Marseille ?

Effectivement dans le code, je ne gère que les lignes "directes" (sans changement)

du coup, par rapport à cela, comment imaginez vous la chose ?

est ce que si on imagine un affichage comme ci dessous ça pourrait aller ?:
lun. 4 nov 08h15
> changement à Marseille à XhYY
> changement à ZZZ à ____

Je peux tenter de faire ça, mais j'avoue ne pas être expert de cette techno où je "bidouille"

**Comment by chassain** [comment]
Il existe pourtant des directs sans passer par marseille..donc ca devrait fonctionner.

**Comment by chassain** [comment]
Le changement serait pas mal oui j avoue..est ce que tu as un resultat avec ces id stations ?

**Comment by tsoonav** [comment]
Non je n'ai rien...
il ne connait pas l'arrêt

```
// https://api.sncf.com/v1/coverage/sncf/journeys?to=stop_area:OCE:SA:876860006&from=stop_area:OCE:SA:87755009&count=3

{
  "tickets": [
    
  ],
  "links": [
    
  ],
  "disruptions": [
    
  ],
  "notes": [
    
  ],
  "feed_publishers": [
    
  ],
  "context": {
    "timezone": "Europe/Paris",
    "current_datetime": "20191104T093829"
  },
  "error": {
    "message": "The entry point: stop_area:OCE:SA:876860006 is not valid",
    "id": "unknown_object"
  },
  "exceptions": [
    
  ]
}
```

**Comment by tsoonav** [comment]
Essaye avec 

```
to=stop_area:OCE:SA:87686006
from=stop_area:OCE:SA:87755009
```

ça semble pas mal

**Comment by chassain** [comment]
Yes..dès que je rentre..mais il me semble avoir testé ceci déjà..faut que je vois..merci en tout cas..je te ferai un retour

**Comment by tsoonav** [comment]
Avec ces valeur, j'ai qq chose.

Après je te dis ça depuis l'API SNCF.
je n'ai pas de plateforme de test du module.

de mémoire, dans le code, je ne prenais que les sections qui n'étaient pas `Walking` mais je n'ai jamais géré le fait qu'il puisse y avoir un changement de gare car ce n'étais pas mon besoin.

Là, SNCF me donne un train qui part à 11h48 de Toulon, un TGV InOui qui arrive à Paris à 16h15 ?
le suivant part de Toulon à 13h26, arrive à Marseille à 14h27, de là, attente jusque 14h57 pour un TGV qui arrive à Paris à 18h23.

Est ce que tu peux confirmer ces infos ?

A voir ensuite comment on gère ça dans le module...

**Comment by chassain** [comment]
Je te fais un retour en début d après midi

**Comment by chassain** [comment]
En remplaçant to et from avec departuic et arriveeuic je n ai pas mieux

**Comment by tsoonav** [comment]
Il faut que je teste à la maison.
J'essaye de faire ça rapidement :)

**Comment by tsoonav** [comment]
Bonjour,
j'ai pu tester ce jour.
J'ai fait qq modifs dans le code.
J'ai bien les heures de départ, mais c'est pas encore l'idéal
il faut que je passe plus de temps à tout modifier le code, notamment pour ajouter les changements et pour prendre en compte la durée globale du trajet et pas la durée du premier trajet (et de mettre en forme un peu plus sympa si on est à plus d'1h de trajet, pas laisser en mn)
![Capture du 2019-11-08 10-28-37](https://user-images.githubusercontent.com/30594988/68465449-d0903500-0212-11ea-9272-96263e56a196.png)

**Comment by chassain** [comment]
Bonjour,

testé aussi. y a du mieux c'est clair, pouvant afficher le toulon paris. Bravo déjà pour cela.. J'essaye de t'aider au mieux mais sans connaissance ça m'est difficile pour moi..J'essaye de prendre un maximum d'infos sur d'autres forums ou de voir d'autres scripts pour des modules similaires...

**Comment by chassain** [comment]
salut chef,

quelques problèmes depuis peu pour accéder aux données sur l'écran
`0|mm  | TypeError: Cannot read property 'substring' of undefined
0|mm  |     at Class.processTransports (/home/pi/MagicMirror/modules/MMM-SNCF/node_helper.js:186:21)
0|mm  |     at /home/pi/MagicMirror/modules/MMM-SNCF/node_helper.js:60:9
0|mm  |     at Request.handleRequestResponse [as _callback] (/home/pi/MagicMirror/modules/MMM-SNCF/node_modules/unirest/index.js:552:70)
0|mm  |     at Request.self.callback (/home/pi/MagicMirror/modules/MMM-SNCF/node_modules/request/request.js:185:22)
0|mm  |     at Request.emit (events.js:182:13)
0|mm  |     at Request.<anonymous> (/home/pi/MagicMirror/modules/MMM-SNCF/node_modules/request/request.js:1161:10)
0|mm  |     at Request.emit (events.js:182:13)
0|mm  |     at IncomingMessage.<anonymous> (/home/pi/MagicMirror/modules/MMM-SNCF/node_modules/request/request.js:1083:12)
0|mm  |     at Object.onceWrapper (events.js:273:13)
0|mm  |     at IncomingMessage.emit (events.js:187:15)
`

tu as ce pb ?

**Comment by chassain** [comment]
`0|mm  | TypeError: Cannot read property 'substring' of undefined
0|mm  |     at Class.processTransports (/home/pi/MagicMirror/modules/MMM-SNCF/node_helper.js:186:21)
0|mm  |     at /home/pi/MagicMirror/modules/MMM-SNCF/node_helper.js:60:9
0|mm  |     at Request.handleRequestResponse [as _callback] (/home/pi/MagicMirror/modules/MMM-SNCF/node_modules/unirest/index.js:552:70)
0|mm  |     at Request.self.callback (/home/pi/MagicMirror/modules/MMM-SNCF/node_modules/request/request.js:185:22)
0|mm  |     at Request.emit (events.js:182:13)
0|mm  |     at Request.<anonymous> (/home/pi/MagicMirror/modules/MMM-SNCF/node_modules/request/request.js:1161:10)
0|mm  |     at Request.emit (events.js:182:13)
0|mm  |     at IncomingMessage.<anonymous> (/home/pi/MagicMirror/modules/MMM-SNCF/node_modules/request/request.js:1083:12)
0|mm  |     at Object.onceWrapper (events.js:273:13)
0|mm  |     at IncomingMessage.emit (events.js:187:15)
`

**Comment by jerome-pouiller** [comment]
Je ne suis pas développeur javascript, mais je pense que le patch suivant doit résoudre le problème:
```
diff --git a/node_helper.js b/node_helper.js
index 7e0b12b..4c328fe 100644
--- a/node_helper.js
+++ b/node_helper.js
@@ -180,7 +180,7 @@ processTransports: function(data) {
                                                console.log("\r\nDisruption info: ");
                                                console.log(_disruptionInfo);
                                        }
-                                       if(_disruptionInfo !== 0)
+                                       if(_disruptionInfo !== 0 && _disruptionInfo.hasOwnProperty("amended_departure_time"))
                                        {
                                                _date = _disruptionInfo.amended_departure_time;
                                                _date = _date.substring(_date.lastIndexOf(" ")+1);
```

**Comment by tsoonav** [comment]
Désolé, je n'avais pas vu les messages. les mails d'alertes étaient dans un dossier que je ne voyais pas
je pousse la modif de @jerome-pouiller 
question novice en js, le `hasOwnProperty` c'est bien une fonction qui vérifie si la clé existe ?
Bonne journée

**Comment by tsoonav** [comment]
@chassain tu peux confirmer que ça fonctionne bien ? :)

**Comment by chassain** [comment]
Bonjour à tous,

J'ai testé. Les trains s'inscrivent oui mais aucun temps de parcours (tout en blanc)..et toujours les invalid data sur les trains qui font des arrêts entre toulon et paris

**Comment by tsoonav** [comment]
> Bonjour à tous,
> 
> J'ai testé. Les trains s'inscrivent oui mais aucun temps de parcours (tout en blanc)..et toujours les invalid data sur les trains qui font des arrêts entre toulon et paris

Bonjour,
De nouvelles mises à jour ont été proposée par un contributeur au module.
Normalement ça devrait fonctionner maintenant.

**Comment by Sisyphe7005** [comment]
Bonjour à tous,
Je débute totalement dans l'utilisation de MM et de ses modules je vous demande donc d'être indulgents si la quetion est stupide. 
Après plusieurs essais je suis parvenu a faire fonctionner le module mais un problème me résiste sur les horaires de départ de trains affichés, Je n'ai que des horaires qui finisent par 04 minutes : 16H04, 17H04 .... quel que soit l'horaire réel du train. Comment faire pour obtenir la vraie heure de départ ?
gare de départ : 87682005
gare d'arrivée : 87686006
Merci pour votre aide

**Comment by tsoonav** [comment]
Bonjour @Sisyphe7005 ,
je viens de tester chez moi, j'ai ces infos
![image](https://user-images.githubusercontent.com/30594988/80188946-30886580-8612-11ea-8a9b-b379dd0fccc1.png)
Est ce que ça correspond à vos horaires ?

**Comment by Sisyphe7005** [comment]
bonjour et merci de me repondre,
En effet, vous avez les bon horraires cotrairement a moi.
Du coup, que puis-je modifier pour résoudre mon problème ?
Config PI3, l'aplli est à la bonne heure. 
seule différence que je vois c'est l'affichage de la date, moi j'ai : vendredi 11:04, pas de mois ni d'année

**Comment by tsoonav** [comment]
Voilà la config du module chez moi :
```
{
			module: "MMM-SNCF",
			position: 'top_left',
			header:'Orchies vers Lille-Flandre',
			config:{
				id: '1',
				departUIC: "stop_point:OCE:SP:TrainTER-87286583", // Orchies
				arriveeUIC: "stop_point:OCE:SP:TrainTER-87286005", //Lille Flandre 
				trainsdisplayed: '3',
				language: "fr",
				apiKey: "XXXXXXXXXXXXX",
				displayHeader: false,
				displayName: false,
				displayC02: false,
				debugging: false,
			}
		},
```

**Comment by Sisyphe7005** [comment]
rien ne vaut une bonne config pour trouver un défaut .... Grâce a ta config, jai pu voir comme mis en copire que j'avais un dateFormat dans la mienne. si je le passe en commentaire ça fonctionne.
je ne sais pas pourquoi cette fonction c'est retrouvée ici.
Merci pour ton aide 

	{
    module: 'MMM-SNCF',
    position: 'top_left',
    header: 'Melun vers Paris',
    config:{
        departureStationUIC: "stop_area:OCE:SA:87682005",
        arrivalStationUIC: "stop_area:OCE:SA:87686006",
        apiKey: "XXXXXXXXXXXXXXXXXXX", // You must add your API key
	numberDays: 3,
        dateFormat: 'dd DD MMMM YYYY HH:MM',
        displayCo2: false,
    }
},

**Comment by tsoonav** [comment]
> je ne sais pas pourquoi cette fonction c'est retrouvée ici.

C'est parce qu'avec les dernière mises à jour, tu peux paramétrer le mode d'affichage de la date.
Et là tu as une erreur sur ton format parce que ton format HH:MM (j'ai vérifié la doc moment.js) tu demandes l'heure en format 24h, là tout va bien, mais MM ainsi écrit, tu demandes le mois en chiffres, d'où le fait que tu aies 04 en ce moment ;)
si tu veux les minutes il faut mettre mm (en minuscule)

Bonne journée

ps : je me permets de clore cette issue pour ne pas polluer la personne à l'origine du post :)
en cas de pb, n'hésite pas à en faire une autre
