### ISSUE TITLE
destination

### ISSUE THREAD

**Issue by chassain** [jvanoost/MMM-SNCF#10]
Re bonjour,

toujours un plaisir avec ce module. J'utilise aussi le module widget pour taper l'adresse du site de la sncf..Evidemment, tous les 2 mois, cela ne marche plus pour l'accès. Mais du coup je me demandais s'il était possible de ne plus renseigner la destination et de voir ainsi tous les trains au départ d'une gare et avoir les destinations de renseignées.

au plaisir

**Comment by abrochet** [comment]
Bonjour, 
De mémoire ce n'est pas le même appel... mais je pense que c'est possible d'adapter le code.
Je pourrais jeter un coup d'oeil prochainement et vous faire un retour à ce moment-là ;)
A bientôt.

**Comment by chassain** [comment]
Super..en attendant j attends toujours d afficher la vache sur le rail à cuers 😁.
Bonne journée

**Comment by tsoonav** [comment]
ça a l'air possible, via navitia
[http://doc.navitia.io/#next-departures-and-arrivals](http://doc.navitia.io/#next-departures-and-arrivals)
mais dans ce cas est ce qu'un nouveau module ne serait pas plus approprié ?

**Comment by abrochet** [comment]
@chassain j'avoue j'ai un peu triché 😉 depuis que je suis arrivé dans le sud je n'ai pas vu beaucoup de vache.
@jvanoost c'est la question que je me pose après si c'est la même trame de données je pense qu'un nouveau module n'est pas nécessaire. Il faudrait juste faire un switch sur l'appel à l'API. Je peux faire des tests dans une quinzaine de jours sur mon compte et si le résultat convient à tout le monde on basculera les modifications sur le module ça vous va ?

**Comment by chassain** [comment]
Si seulement l'information mentionne une vache :)... Mais oui carrément pour..Maintenant je ne comprends pas pourquoi l'affichage d'une page Iframe avec le module MMM-Widget2 marche seulement un temps pour ce site..Je dois faire trop d'appels à cette page
@+

**Comment by abrochet** [comment]
Je ferme cette demande vu qu'elle fait doublon avec [celle-là.](https://github.com/jvanoost/MMM-SNCF/issues/11 )
