### ISSUE TITLE
Question about state and others

### ISSUE THREAD

**Issue by chassain** [jvanoost/MMM-SNCF#11]
Salut,

![image](https://user-images.githubusercontent.com/32990929/94984702-31bda700-054f-11eb-8ca3-13179fbffea4.png)

do i understand "reduced service" is "perturbations" ? 
i have always "undefined" below "on time". Is it normal ?
did you work about new api to have all destinations about a station ?

have a good day

**Comment by abrochet** [comment]
Bonjour,

Je n'ai pas eu le temps de me pencher sur votre demande d'évolution, mais je vais essayer de le me dégager un peu de temps pour regarder si c'est envisageable. 
Concernant le premier point, je viens de livrer du code sur la branche "dev". Si jamais vous êtes à l'aise avec git vous pouvez tester les remontées d'informations concernant les perturbations s'il vous plaît ? Par contre j'ai l'impression que les délais pour les retards ne sont pas remontée de la même façon avec la nouvelle API ... Il faut que je pousse mes tests un peu plus loin !

**Comment by chassain** [comment]
Bonjour,

c'est sympa de ta part. J'ai travaillé sur un autre concept en attendant , n'ayant aucune notion de programmation mais je trouve toujours des solutions plus ou moins belles. Concernant les horaires de train, j'ouvre une page web des départs en gare de toulon sur un autre serveur fictif et je prends une capture que j'affiche ensuite toutes les 5 min avec un module MMM-Image..Ca marche vraiment bien. Ton module est très bien aussi mais j'avoue que là j'ai tous les départs en gare (voir arrivée si on veut) sans donner une destination.

**Comment by abrochet** [comment]
@chassain c'est une bonne idée la capture et c'est toujours enrichissant sur le plan personnel de trouver une solution à un problème tout seul.
Pour le module je n'ai fait qu’apporter une pierre à l'édifice du module de @jvanoost 

Sinon j'ai développé un petit truc vite fait que je viens d'envoyer sur la branche "dev".
Il y a un nouveau paramètre "mode" qui a pour le moment deux valeurs possible 0 ou 1.

Chez moi ça donne ça :
 
![image](https://user-images.githubusercontent.com/24960001/120381041-3c208280-c322-11eb-9172-611139d66f36.png)

Il y a une ou plusieurs valeurs que l'API ne remonte pas il faudra donc désactiver les colonnes en question !

Notamment le C02, le statut du train et la durée ! 
Pour la durée je pense qu'on peut faire un calcul avec la date / heure de départ et la date / heure d'arrivée.

C'est drôle, la France est petite je viens de remarquer que tu es sur Toulon ;)

Dans l'attente de ton retour,

**Comment by chassain** [comment]
hello,

ca semble prometteur. Je suis même de Hyeres mais je bosse à Toulon. Qu'est ce que j'aimerais être développeur. J'ai bien tenté à 45 ans mais je m'y perds rapidement. Néanmoins j'ai lancé ma petite micro entreprise dans les écrans connectés et j'adore y passer du temps dessus, pour rendre certains écrans qu'on trouve en vitrine plus dynamique. On aura peut être l'occasion d'en parler plus longuement un jour. Je testerai cette nouvelle branche. Bravo à toi en tout cas

**Comment by chassain** [comment]
tes horaires correspondent bien lorsque je fais un scan me de ma photo plus haut :)

**Comment by abrochet** [comment]
C'est bien d'avoir une idée et de monter ça propre entreprise. 
C'est sûr le monde de la programmation est vaste... Il y a tellement de langage...
Pour le module c'est une bonne nouvelle s'il fonctionne ! Par rapport à ta capture il y a des informations que je n'affiche pas ?
Quand j'aurai un peu de temps je désactiverai les colonnes qui n'ont pas d'informations + une ou deux autres améliorations.

**Comment by chassain** [comment]
![20210602_171112](https://user-images.githubusercontent.com/32990929/120508585-24033e80-c3c8-11eb-9c88-ef802b209f23.jpg)

**Comment by abrochet** [comment]
Bonjour @chassain 
Je viens de livrer les dernières modifications avec le masquage des colonnes.
Si c'est possible de me faire un retour et si ça convient on clôture la demande ;)
A+

**Comment by chassain** [comment]
Bonjour. Je teste cela ce soir et te fais un retour immédiat :)

**Comment by chassain** [comment]
La table n'est pas remplie. Tout est blanc

**Comment by abrochet** [comment]
Étrange je n'ai pas de soucis chez moi : 
![image](https://user-images.githubusercontent.com/24960001/121413037-9397a180-c965-11eb-9e2c-ffbfe1c540da.png)
Je peux avoir ta config stp ? Merci

**Comment by chassain** [comment]
j'ai pris celle du read me en ayant installé le git clone code à partir de la branch dev..j'ai dû rater un truc

**Comment by chassain** [comment]
j'avais une vieille configuation css..c'est mieux mais pas de téléchargement des trains

**Comment by chassain** [comment]
c 'est bon..:)..faut que je re paremètre pour ma ligne du coup

**Comment by abrochet** [comment]
Ah super ça venait de quoi ?

**Comment by chassain** [comment]
j'ai pris la conf d'un gars. l'exemple read me posait problème je pense..
