### ISSUE TITLE
Chargement des prochains trains...

### ISSUE THREAD

**Issue by maxencekyz** [jvanoost/MMM-SNCF#12]
Bonjour @abrochet  et @jvanoost ,

Impossible d'avoir les horaires sur mon écran, j'ai sans cesse "Chargement des prochains trains..."

![image](https://user-images.githubusercontent.com/80335419/111037034-abbd5a80-8422-11eb-944d-f7a5f33ad390.png)

Voici ma config :

> {
			module: 'MMM-SNCF',
			position: 'bottom_left',
			header: 'Prochain train',
			config:{
				departureStationUIC: "stop_area:OCE:SA:87286005", // identique au config d'origine
                                arrivalStationUIC: "stop_area:OCE:SA:87286583", // identique au config d'origine
				apiKey: "xxxxxxxx", 
			        numberDays: 1,
				updateInterval: 300000,
				initialLoadDelay: 5000,
				dateFormat: 'dddd HH:mm', // display for example with french locale Jeudi 08:43
				displayCo2: false,
			}
		},

Une idée sur comment résoudre le problème ?
Merci d'avance,
- Maxence

**Comment by tsoonav** [comment]
Bonjour,
J'ai le même problème en ce moment, faut que je fasse du début...
Je vous tiens au courant

**Comment by maxencekyz** [comment]
Merci beaucoup,
En attente de votre retour,

Malheureusement je ne m'y connais pas en programmation bon courage

**Comment by tsoonav** [comment]
il y a un soucis dans l'appel à l'API SNCF qui renvoie une erreur.
Il faut creuser pour comprendre cette erreur, pourquoi d'un coup la donnée n'est plus valide...
```
"message": "The entry point: stop_point:OCE:SP:TrainTER-87286583 is not valid",
```

**Comment by GuerrierAlpha** [comment]
bonjour et avant tout un grand merci pour votre travail

j'utilise le module depuis 2 ans avec grande joie. J'ai le même souci que vous depuis quelques jours. J'ai réinstallé le module, puis le MMM depuis le début, sans succès. Avant de me rendre compte ici que le problème était commun. 

Je ne peux pas vraiment vous aider à développer mais à votre disposition pour tester des solutions

**Comment by maxencekyz** [comment]
J'ai fait plusieurs test, sans succès.
Avis aux codeurs aguerris pour solutionner le problème!
Excellente journée,

**Comment by tsoonav** [comment]
Bonjour,

pour info, j'ai pris contact avec la SNCF pour comprendre ce qu'il se passe parce que même avec leur exemple sur leur site ça plante...

**Comment by maxencekyz** [comment]
Bonjour,

Entendu, c'est génial ! Hate de voir le résultat :))
Encore merci

**Comment by tsoonav** [comment]
J'me demande s'ils n'ont pas changé leur API et qu'il faudra utiliser l'API Navitia...
Pour moi ça donne : https://api.navitia.io/v1/coverage/fr-ne/journeys?from=stop_area%3ASTE%3ASA%3AOCE87286005&to=stop_area%3ASTE%3ASA%3AOCE87286583&
Du coup faudrait changer le code pour passer sur ce modèle, il faudrait mettre la couverture, mais je ne sais pas laquelle, a priori la zone de départ, fr-ne pour moi dans le nord

**Comment by tsoonav** [comment]
J'ai testé avec navitia chez moi, ça fonctionne !

Si quelques personnes peuvent tester la branche **dev**
@abrochet si tu peux le tester aussi (c'est qd même toi qui a fait évoluer le projet)

Attention, il y a quelque ajustements à faire dans le fichier config et demander une nouvelle clé API chez navitia.io

Faites moi vos retours et si tout roule, on la passera en prod

**Comment by tsoonav** [comment]
Hello est ce que vous avez pu regarder @maxencekyz  @abrochet @GuerrierAlpha  ?
chez moi je tourne en test depuis que j'ai poussé la branche de dev, et ça tourne bien

**Comment by maxencekyz** [comment]
Bonjour @jvanoost , n'y connaissant strictement rien, je ne sais pas comment linker navitia et le module SNCF...
Je suis toujours au même point.
Auriez-vous plus d'informations sur la marche à suivre ? Plus particulièrement dans le fichier config ?
Merci d'avance

**Comment by abrochet** [comment]
Bonjour @jvanoost,
Désolé pour la réponse plus que tardive, je ne suis plus trop disponible en ce moment mais je vais essayer de prendre un moment dans la semaine pour tester la modification et faire un retour.
Je reviens vers vous d'ici dimanche maxi promis ;) 
A+

**Comment by tsoonav** [comment]
> Bonjour @jvanoost , n'y connaissant strictement rien, je ne sais pas comment linker navitia et le module SNCF...
> Je suis toujours au même point.
> Auriez-vous plus d'informations sur la marche à suivre ? Plus particulièrement dans le fichier config ?
> Merci d'avance

Regarde la branche dev, j'ai mis ce qu'il faut dans le readme normalement ;)

**Comment by tsoonav** [comment]
> Bonjour @jvanoost,
> Désolé pour la réponse plus que tardive, je ne suis plus trop disponible en ce moment mais je vais essayer de prendre un moment dans la semaine pour tester la modification et faire un retour.
> Je reviens vers vous d'ici dimanche maxi promis ;) 
> A+

Je comprends j'ai aussi eu des soucis de dispo il y a qq temps ;)

**Comment by tsoonav** [comment]
> Bonjour @jvanoost , n'y connaissant strictement rien, je ne sais pas comment linker navitia et le module SNCF...
> Je suis toujours au même point.
> Auriez-vous plus d'informations sur la marche à suivre ? Plus particulièrement dans le fichier config ?
> Merci d'avance

Hello,
J'étais sur mobile hier soir, donc plus galère.
Voilà la lien vers comment faire avec la nouvelle version : https://github.com/jvanoost/MMM-SNCF/blob/dev/README.md

Il te faut créer un compte ici : https://www.navitia.io/
Ensuite tu récupéreras une clé API que tu pourras mettre en lieu et place de celle SNCF.
Tu remplaces ensuite tes id de départ et arrivée, chez moi c'est` stop_point:OCE:SP:TrainTER-87286005` qui deviennent `stop_area:STE:SA:OCE87286005` du coup, pas trop dur de migrer de l'un vers l'autre :)
Tu peux ensuite aller voir ici dans quel "secteur" SNCF tu te trouves : https://navitia.opendatasoft.com/explore/?sort=modified&refine.geographicarea=France, ou alors sur la carte ici : https://www.navitia.io/datasets, tu prends un ville pres de chez toi et tu regardes le _coverage_
et tu ajoutes la param coverage dans le fichier config
`coverage: "fr-ne",` dans mon cas.

J'espère que c'est assez clair ;)

**Comment by abdelhadj** [comment]
Bonjour,
J'ai du mal à comprendre comment trouver la gare de départ et d'arrivée? je cherche deux ligne sur le RER A
Coverage : fr-idf on dirait 
Merci d'avance :)

**Comment by tsoonav** [comment]
Bonjour,
Le plus simple je pense est de passer par le playground Navitia : https://canaltp.github.io/navitia-playground/play.html
Tu rentres ton token, et à partir de là tu peux "jouer" avec tous les attributs.
Par exemple j'ai mis fr-idf, et dans stop_area j'ai commencer à taper montparnasse, et dès qu'on clique sur une station dans la liste qui apparait, on récupère le code de la station dans le champ.
![image](https://user-images.githubusercontent.com/30594988/119616621-19add700-be01-11eb-813e-7fa5659dd709.png)

Il y a peut être plus simple mais je n'ai pas encore trouvé d'autre solution plus facile...

**Comment by abdelhadj** [comment]
Super ça aide!
le module affiche par défaut les deux prochains trains c'est normal? et parfois 4 trains mais les deux derniers sont un bug (cela arrive le soir c'est moins gênant)
J'ai également sous "particularité " : Significant_delay en jaune et undefined en gris en permanence, je ne pense pas que ce soit "retard de train" , si?

**Comment by tsoonav** [comment]
Bonjour,

concernant le nombre de lignes affichées, c'est la paramètre `numberDays` (chez moi et dans la première version j'ai 
`trainsdisplayed`)

Concernant les undefined, si c'est peut être des retards, là chez moi il n'y a pas d'alertes, j'ai ceci 
![image](https://user-images.githubusercontent.com/30594988/120155888-a259b800-c1f1-11eb-9a87-c32909119d25.png)
Mais parfois il y a des retards sans explications, du coup, c'est la source du undefined. Après j'suis moins à l'aise avec cette partie, c'est pas moi qui l'ai développée ;)

**Comment by abrochet** [comment]
Bonjour,
Je vais essayer de regarder cette semaine. J'ai eu un peu de mal à redémarrer ma raspberry, j'ai dû réinstaller le module MagicMirror, il faut que j'essaye de reconfigurer le plugin MMM-SNCF maintenant ! Et quand ça sera bon je pourrais faire un test pour les retards.

**Comment by abrochet** [comment]
@abdelhadj Je viens de livrer du code sur la branche "dev". Si jamais vous êtes à l'aise avec git vous pouvez tester les remontées d'informations concernant les perturbations s'il vous plaît ? Par contre j'ai l'impression que les délais pour les retards ne sont pas remontée de la même façon avec la nouvelle API ... Il faut que je pousse mes tests un peu plus loin !

**Comment by abdelhadj** [comment]
bonjour, je ne suis familier avec git malheureusement, voila ce que j'obtiens parfois, numberDays n'a aucune influence
`			config:{
				departureStationUIC: "stop_area:0:SA:8738640",
				arrivalStationUIC: "stop_area:0:SA:8775860",
				apiKey: "f64b40ca-7e6d-4860-9ef8-290f8648d238", // You must add your API key
				numberDays: 2,
				maxNbTransfers:10,
				trainsdisplayed:2,
				dateFormat: 'dddd HH:mm', // display for example with french locale Jeudi 08:43
				displayCo2: false,
				coverage: "fr-idf",
			}`

![defaut_trains](https://user-images.githubusercontent.com/17235411/121254425-836ebc00-c8aa-11eb-95e1-007643db5e83.JPG)

**Comment by abdelhadj** [comment]
Bonjour, je ne maitrise pas git malheureusement. Voila ce que j'obtiens, et NumberOfDays n'a aucune influence.
`			config:{
				departureStationUIC: "stop_area:0:SA:8738640",
				arrivalStationUIC: "stop_area:0:SA:8775860",
				apiKey: "f64bxxxx", // You must add your API key
				numberDays: 2,
				maxNbTransfers:10,
				trainsdisplayed:2,
				dateFormat: 'dddd HH:mm', // display for example with french locale Jeudi 08:43
				displayCo2: false,
				coverage: "fr-idf",
			}`

![defaut_trains](https://user-images.githubusercontent.com/17235411/121254703-e06a7200-c8aa-11eb-9811-020bdde32414.JPG)

**Comment by abrochet** [comment]
Bonjour,

@abdelhadj Je viens de livrer des modifications sur la branche : "dev" qui normalement corrige 90 % de vos remontés.

Vous avez installé le module comment ? Pour utiliser la branche : "dev" il faut se positionner dans le dossier "MMM-SNCF" et lancer les deux commandes ci-dessous :

git checkout dev
git pull

@jvanoost Je laisse mes modifications sur la banche : "dev" quelques semaines et si c'est concluant je te propose de les basculer sur la banche : "master".

A+

**Comment by solid38** [comment]
Bonjour,
Je viens de tester le module, et j'ai toujours le message "Chargement des prochains trains...".
J'ai essayé avec l'exemple fourni, mais ça ne fonctionne pas. D'ailleurs, que ce soit sur la branche master ou la branche dev, le problème est identique. 
J'ai testé le playground de nativia, et j'obtiens des résultats, comme le montre l'image ci-dessous. J'estime donc que mon apiKey est bonne.

![image](https://user-images.githubusercontent.com/54800337/126743109-3b7c4d04-83a4-411d-89d9-5b52c1d16e1a.png)

Malheureusement, sur le miroir, je n'ai aucun résultat.
Ci-dessous le test avec l'exemple fourni : 

![image](https://user-images.githubusercontent.com/54800337/126743191-1fb6bb4d-458a-4d1b-be86-d2d3bf817233.png)

Le code utilisé : 

```
{
		module: 'MMM-SNCF',
		position: 'top_right',
		header: 'Lille-Flandres to Orchies',
		config:{
			departureStationUIC: "stop_area:OCE:SA:87286005",
			arrivalStationUIC: "stop_area:OCE:SA:87286583",
			apiKey: "aa491f52-xxxxxxxxxxxxxxxxxxxxxxxxxxx", // You must add your API key
			numberDays: 2,
			dateFormat: 'dddd HH:mm', // display for example with french locale Jeudi 08:43
			displayCo2: true,
			coverage: "fr-ne",
		}
	},
```
Je suis actuellement sur la branche dev : 

![image](https://user-images.githubusercontent.com/54800337/126743266-b6546ed4-9320-4f9c-a1a6-4161eed30c87.png)

Avez-vous une idée ? 
Merci d'avance :)

**Comment by solid38** [comment]
My bad, ça fonctionne aujourd'hui ;)
Je n'ai pourtant pas fait de changement notable. 
A voir sur la durée ;)

**Comment by tsoonav** [comment]
> My bad, ça fonctionne aujourd'hui ;)
> Je n'ai pourtant pas fait de changement notable.
> A voir sur la durée ;)

Désolé je ne vois le message que maintenant, ça a l'air d'aller ;)
