### ISSUE TITLE
Horaires affichés temps réel ?

### ISSUE THREAD

**Issue by tet102** [jvanoost/MMM-SNCF#4]
Salut jvanoost...merci pour la maj maintenant j'arrive à avoir les horaires de trains sur ma ligne préférée....Super job.
Une question les horaires affichés sont-ils  des horaires en temps réels (retards pris en compte)...ou seulement les horaires théoriques.
Sinon pourrais-tu me dire si c'est difficile de faire afficher les horaires en temps réels ?
Merci pour ta réponse..
Cdlt
Stpehane

**Comment by tsoonav** [comment]
je t'en prie !
ce sont les horaires temps réel depuis le portail open data de la SNCF : [Portail API SNCF](https://www.digital.sncf.com/startup/api)

chez moi ça m'affiche bien quand le train est en retard, avec le nouvel horaire qui est affiché

N'hésite pas si tu veux apporter des améliorations, ça sera avec grand plaisir !

**Comment by link5959** [comment]
bonjour 
Merci pour le super job sur le module 
par ailleurs j'ai un petit problème, les horaires qui s'affichent sur le mm entre mes 2 gares de référence sont faux 
le numéro du train par contre est bon sais tu d'ou peut provenir le problème ? 
merci 
Cdt 
camille

**Comment by abrochet** [comment]
Bonjour,
Si le problème persiste avec la dernière version, pourriez-vous créer un nouveau problème?
Pour l'instant, je ferme ce vieux ticket.
