### ISSUE TITLE
Problème d'horaires 

### ISSUE THREAD

**Issue by link5959** [jvanoost/MMM-SNCF#8]
bonjour 
Merci pour le super job sur le module 
par ailleurs j'ai un petit problème, les horaires qui s'affichent sur le mm entre mes 2 gares de référence sont faux 
le numéro du train par contre est bon sais tu d'ou peut provenir le problème ? 
merci 
Cdt 
camille

_Originally posted by @link5959 in https://github.com/jvanoost/MMM-SNCF/issues/4#issuecomment-633180894_

**Comment by abrochet** [comment]
Bonjour,

Il faudrait nous communiquer l'identifiant de la gare de départ et d'arrivée s'il vous plaît.
(departureStationUIC & arrivalStationUIC)

Merci,
Anthony

**Comment by tsoonav** [comment]
ça sent un pb de config du format de date, tu as peut être écrit la date pour avoir l'heure avec le format HH:MM
 HH:MM (j'ai vérifié la doc moment.js) tu demandes l'heure en format 24h, là tout va bien, mais MM ainsi écrit, tu demandes le mois en chiffres, si tu veux les minutes il faut mettre mm (en minuscule)

**Comment by abrochet** [comment]
Bonjour,
Si le problème persiste avec la dernière version, pourriez-vous créer un nouveau problème?
Pour l'instant, je ferme ce vieux ticket.
