### ISSUE TITLE
Numéro de voie

### ISSUE THREAD

**Issue by BillAx579** [jvanoost/MMM-SNCF#9]
Bonjour à tous,

Je voudrais savoir si c'est possible de récupérer le numéro de voie ?

Dans mon cas j'ai plusieurs voie possible pour la même destination.

Merci d'avance
Bonne journée !

**Comment by tsoonav** [comment]
bonjour,
pas sur que l'info soit disponible dans l'API, faudrait qu'on vérifie si elle est disponible et si oui, on pourrait alors voir pour l'ajouter

**Comment by tsoonav** [comment]
Je viens de checker ce qui remonte dans l'API, je ne vois pas le numéro de voie nulle part.
Je ne sais pas où on pourrait trouver cette info

**Comment by abrochet** [comment]
Bonjour, 
Idem j'ai regardé et je ne trouve pas l'information. Apparemment le numéro de voie est disponible uniquement 20 minutes avant l'arrivée en gare du train mais je n'ai pas l'impression que l'API retourne l'info...
